spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  security:
    viewer-user: viewer
    viewer-password: viewer123
    admin-user: admin
    admin-password: admin123